### ISSUE TITLE
How to even start using the EC integration in home assistant ?

### ISSUE THREAD

**Issue by HuguesD** [danobot/entity-controller#264]
Hi,
I'm a noob in home asisstant. I have installed your EC integration. I can see it in the list of HACS integrations. But how do I use it ? I cannot find nowhere a button to start configuring a scenario ?

I find explanations in your documentation wiki but nothing on how to start using it after installation?

thanks

**Comment by kozakmuz** [comment]
I think there is a bug! This integration is not working.

**Comment by bravolavo** [comment]
I also experience the bug, and can't install it. It lists itself in HACS, but I cannot see it listed in HA's integrations (I have installed HACS repositories before and after). Let me know if I can test anything (I don't have coding skills to offer).

**Comment by PiotrMachowski** [comment]
you have to configure it in configuration.yaml

**Comment by HuguesD** [comment]
> you have to configure it in configuration.yaml

The question I believe for all of us having trouble is : how ? A step by step description would be nice.

**Comment by PiotrMachowski** [comment]
everything is in documentation: https://danobot.github.io/ec-docs/

**Comment by calisro** [comment]
Doesn't appear in integrations search after HACS install however.
