### ISSUE TITLE
Night Mode: entity select 

### ISSUE THREAD

**Issue by kotarokun** [danobot/entity-controller#284]
## Description
I want to know, if it is Possible, to select some entities for night Mode? I have some light, that don't want to enable in night Mode because it is too bright. 

Thanks a lot

**Comment by ndbroadbent** [comment]
Hi @kotarokun, yes you can do that by setting up multiple entity controllers and setting `start_time` and `end_time` options. There is also a `night_mode` option where you can reduce the brightness (if your light has this option.)
I would recommend setting up a separate entity controller for this light and setting an `end_time` or `override`.

**Comment by dankarization** [comment]
@kotarokun's question is a really good one. Basically duplicating the amount of controllers needed to select different entities for daytime and nighttime is a nightmare, if you have a big house. Would love to see this feature inside one controller

**Comment by dankarization** [comment]
Ok, and how to be when "day" entity is currently on and enters constrained more? If you just turn lights off on enter constrained, then you'll left without any lights, because "night" one won't turn off if no new motion activates it
