### ISSUE TITLE
UL Length incompatible with release 2023.4

### ISSUE THREAD

**Issue by robchandhok** [danobot/entity-controller#297]
Upon updating to 2023.4.0 (and .1 later) there are now a lot of these errors:

2023-04-08 11:50:33.049 ERROR (Recorder) [homeassistant.components.recorder.models.context] Error converting ulid ec_27d790_e4f2ce9dacca95da39232d3b6e to bytes: ULID must be a 26 character string: ec_27d790_e4f2ce9dacca95da39232d3b6e

It appears that CONTEXT_ID_CHARACTER_LIMIT is just incompatible, but I don't know enough about it to suggest the change.

See also where used:

https://github.com/danobot/entity-controller/blob/d2fd0a73c580f3ad8cc6d4498492c20b57678cc6/custom_components/entity_controller/__init__.py#L1562

See also this HA issue (closed) which resolved to the "adaptive lighting" custom component, not HA.
https://github.com/home-assistant/core/issues/91019

**Comment by digitalconverg** [comment]
same issue reported as https://github.com/home-assistant/core/issues/91249

**Comment by robchandhok** [comment]
Correct.  Since the recorder component won’t be changed, the custom component has to be updated.

**Comment by digitalconverg** [comment]
Changed the value in const.py from CONTEXT_ID_CHARACTER_LIMIT = 36 to 26 and it appears to have resolved the problem.

**Comment by robchandhok** [comment]
Seems right.  Can you do a PR? but @danobot or someone will have to merge/release it.

**Comment by ndbroadbent** [comment]
I think this might be breaking some of my entity controller instances (but not all.) I might have to downgrade to 2023.3 until it's working again
