### ISSUE TITLE
When there is no motion for x mins then turn off

### ISSUE THREAD

**Issue by Winzy54** [danobot/entity-controller#319]
hello. 
is it possible to use this for: 

when there is no motion for x mins then turn of the light, but if during that x mins there was again a motion then the timer should restart again and start counting x mins. 

so basically the results should be that only when there was no motion at all for x mins then turn off a light. 

thanks in advnace

**Comment by matmoeh** [comment]
Hi,
Try this:

    sensor_type: duration
    sensor_resets_timer: True
