### ISSUE TITLE
Error at boot in Home Assistant / HACS

### ISSUE THREAD

**Issue by rschuiling** [danobot/entity-controller#82]
## Description
Since a couple of days, at every restart of Home Assistant, two errors about Danobot get thrown in the log. Fortunately, it does not prevent startup, but it is confusing. More people are reporting this in the [HACS topic on the Home Assistant forum](https://community.home-assistant.io/t/custom-component-hacs/121727/535).

## Configuration
HACS is installed in Home Assistant.

## Steps to reproduce
Restart Home Assistant with HACS installed.

**Expected behavior**
No errors in the Home Assistant log.

**Actual Behaviour**

## Logs
2019-10-07 16:26:43 ERROR (MainThread) [hacs.repository.integration.danobot.entity-controller] Missing manifest file.
2019-10-07 16:26:43 ERROR (MainThread) [hacs] Validation for danobot/entity-controller failed.

## Version
Not using this entity-controller extension at all, just using HACS is enough to cause the error.

**Comment by patrul** [comment]
Same here
I am not sure if it was there before last update
